### ISSUE TITLE
Cannot process taskwarrior 2.5 export

### ISSUE THREAD

**Issue by towo** [garykl/task2dot#1]
Cheers,

when running the recommended approach, I get:

```
$ task export | python3 task2dot/task2dot.py| dot -Tsvg > test.svg
Traceback (most recent call last):
  File "task2dot/task2dot.py", line 58, in <module>
    tasks = json_from_task_stdin()
  File "task2dot/task2dot.py", line 43, in json_from_task_stdin
    return json.loads('[' + taskwarrioroutput + "]")
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 3)
```

It's valid json:
```
$ task export | json_verify
JSON is valid
```

I'm not sure how the format has changes, but it's currently returning an array of hashes with the task information.

**Comment by TheKevJames** [comment]
@towo here's a quick patch for 2.5+ support -- worked for me, but YMMV.

```
diff --git a/task2dot.py b/task2dot.py
index 56b3c17..3ad6057 100644
--- a/task2dot.py
+++ b/task2dot.py
@@ -39,8 +39,8 @@ def json_from_task_stdin():
     read input from taskwarrior via stdin,
     return list of dictionaries.
     """
-    taskwarrioroutput = ','.join(sys.stdin.readlines())
-    return json.loads('[' + taskwarrioroutput + "]")
+    taskwarrioroutput = ''.join(sys.stdin.readlines())
+    return json.loads(taskwarrioroutput)
 
 
 def exclusion_from_command_line():
diff --git a/taskwarrior2net/task_lib.py b/taskwarrior2net/task_lib.py
index c26b892..af3ef02 100644
--- a/taskwarrior2net/task_lib.py
+++ b/taskwarrior2net/task_lib.py
@@ -24,7 +24,7 @@ def get_udas_from_task_config():
     if os.environ.get('TASKRC') is None:
         config_file = '{0}/.taskrc'.format(os.environ['HOME'])
     else:
-        config_file = '{0}/.taskrc'.format(os.environ['TASKRC'])
+        config_file = os.environ['TASKRC']
 
     with open(config_file, 'r') as rc:
 ```

**Comment by garykl** [comment]
I wasn't here for a while. Thanks for contributing! Fix is commited.
